language: python
python:
  - 3.8
  - 3.7
  - 3.6
sudo: false
dist: focal
services:
  - xvfb
#addons:
#  firefox: latest
#  apt_packages:
#    - pandoc
env:
  matrix:
    - GROUP=python
#matrix:
#  include:
#    - python: 3.7
#      env: GROUP=js
#    - python: 3.8
#      env: GROUP=docs
cache:
  pip: true
  directories:
    - node_modules # NPM packages
    - $HOME/.npm
before_install:
  - pip install -U pip setuptools --quiet
  - nvm install 8 --quiet
  - |
    if [[ $GROUP == python ]]; then
      pip install codecov
    elif [[ $GROUP == js ]]; then
      npm install -g codecov
    fi
install:
  - |
    if [[ $GROUP == python ]]; then
      pip install --upgrade ".[test]"
    elif [[ $GROUP == js ]]; then
      pip install --upgrade -e ".[test]"
#    elif [[ $GROUP == docs ]]; then
#      pip install --upgrade ".[test, examples, docs]"
    fi
before_script:
  # Set up a virtual screen for Firefox browser testing:
  - |
    if [[ $GROUP == js ]]; then
      export CHROME_BIN=chromium-browser
    fi
    git config --global user.email travis@fake.com
    git config --global user.name "Travis CI"
script:
  - |
    if [[ $GROUP == python ]]; then
      EXIT_STATUS=0
      pushd $(mktemp -d)
      py.test -l --cov-report xml:$TRAVIS_BUILD_DIR/coverage.xml --cov=nbtools --pyargs nbtools || EXIT_STATUS=$?
      popd
      (exit $EXIT_STATUS)
    elif [[ $GROUP == js ]]; then
      npm test
    elif [[ $GROUP == docs ]]; then
      EXIT_STATUS=0
      cd docs
      make html || EXIT_STATUS=$?
      make linkcheck || EXIT_STATUS=$?
      cd ..
      python -m pytest_check_links --links-ext=.md -o testpaths=. -o addopts= || EXIT_STATUS=$?
      (exit $EXIT_STATUS)
    fi
after_success:
  - codecov
notifications:
  - slack: genepattern:OAj2q4hee6Mk5v9r6SUCIacZ